apiVersion: v1
kind: PersistentVolume
metadata:
  name: upload-server-files
  labels:
    app: upload-server-files
spec:
  storageClassName: local-storage
  claimRef:
    name: upload-server-files
    namespace: upload-server
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/nfs/downloader
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - unknownpgr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-server-files
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: upload-server-files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-server
  labels:
    app: upload-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-server
  template:
    metadata:
      labels:
        app: upload-server
    spec:
      volumes:
        - name: upload-server-files
          persistentVolumeClaim:
            claimName: upload-server-files
      containers:
        - name: upload-server
          image: upload-server
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/app/download"
              name: upload-server-files
      imagePullSecrets:
        - name: registry-credit
---
apiVersion: v1
kind: Service
metadata:
  name: upload-server
spec:
  selector:
    app: upload-server
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-upload-server
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`downloader.unknownpgr.com`)
      services:
        - name: upload-server
          port: 80
      middlewares:
        - name: traefik-basic-auth
  tls: {}
