apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: upload-server

resources:
  - downloader.yaml
  - middleware.yaml

secretGenerator:
  - name: registry-credit
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson
  - name: traefik-basic-auth
    files:
      - users
    options:
      disableNameSuffixHash: true

images:
  - name: upload-server
    newName: NAME
    newTag: TAG
