apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader
  labels:
    app: downloader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: downloader
  template:
    metadata:
      labels:
        app: downloader
    spec:
      containers:
      - name: downloader
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: downloader
spec:
  selector:
    app: downloader
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-downloader
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`downloader.server.unknownpgr.com`)
    services:
    - name: downloader
      port: 80
  tls: {}