#!/bin/bash

set -e
cd $(dirname $0)/..

TAG=$(git rev-parse --verify HEAD)
NAME=se.ction.link/upload-server
IMAGE=$NAME:$TAG
docker build -t $IMAGE .
docker push $IMAGE

cat kustomize/kustomization.template.yaml\
  | sed "s|NAME|$NAME|"\
  | sed "s|TAG|$TAG|"\
  > kustomize/kustomization.yaml

k apply -k kustomize